### ISSUE TITLE
'Seq2SeqTrainingArguments' object has no attribute 'do_semi_train'

### ISSUE THREAD

**Issue by lcqlalala** [GT-SALT/CODA#2]
Hello, when I run run_summarization.py, I get the following error:
Traceback (most recent call last):
   File "run_summarization.py", line 703, in <module>
     main()
   File "run_summarization.py", line 462, in main
     if training_args.do_train and not training_args.do_semi_train:
AttributeError: 'Seq2SeqTrainingArguments' object has no attribute 'do_semi_train'

**Comment by seamoke** [comment]
I think in the class 'DataTrainingArguments' should add the parameters 'do_semi_train'.

**Comment by seamoke** [comment]
I think in the class 'Seq2SeqTrainingArguments' should add the parameters 'do_semi_train'.

**Comment by frankdarkluo** [comment]
> Hello, when I run run_summarization.py, I get the following error: Traceback (most recent call last): File "run_summarization.py", line 703, in main() File "run_summarization.py", line 462, in main if training_args.do_train and not training_args.do_semi_train: AttributeError: 'Seq2SeqTrainingArguments' object has no attribute 'do_semi_train'

Hi, have you successfully run the code yet?
