### ISSUE TITLE
TypeError: DataCollatorForSeq2Seq got an unexpected keyword argument 'noise_type'

### ISSUE THREAD

**Issue by frankdarkluo** [GT-SALT/CODA#4]
Hello, when I run run_summarization.py, I get the following error:
Traceback (most recent call last):
  File "run_summarization.py", line 702, in <module>
    main()
  File "run_summarization.py", line 538, in main
    data_collator = DataCollatorForSeq2Seq(
TypeError: __init__() got an unexpected keyword argument 'noise_type'

noise_type is `randomutterance2`, but where is it?

**Comment by seamoke** [comment]
> Hello, when I run run_summarization.py, I get the following error: Traceback (most recent call last): File "run_summarization.py", line 702, in main() File "run_summarization.py", line 538, in main data_collator = DataCollatorForSeq2Seq( TypeError: **init**() got an unexpected keyword argument 'noise_type'
> 
> noise_type is `randomutterance2`, but where is it?

The code don't update noise and data augment, you need to add it.

**Comment by mnishant2** [comment]
I am facing the same issue, were you able to fix it? I didn't get the answer provided here, what is the code to add noise, could you give the code for reproducibility, or point us to a source

**Comment by seamoke** [comment]
> I am facing the same issue, were you able to fix it? I didn't get the answer provided here, what is the code to add noise, could you give the code for reproducibility, or point us to a source

The author don't update the code about the part of data augment. Now you can understand that the code only finish the part of semi-training. The 'noise_type' is useless in this repo.

**Comment by mnishant2** [comment]
> > I am facing the same issue, were you able to fix it? I didn't get the answer provided here, what is the code to add noise, could you give the code for reproducibility, or point us to a source
> 
> The author don't update the code about the part of data augment. Now you can understand that the code only finish the part of semi-training. The 'noise_type' is useless in this repo.

Were you able to reproduce the results from the paper?

**Comment by seamoke** [comment]
> > > I am facing the same issue, were you able to fix it? I didn't get the answer provided here, what is the code to add noise, could you give the code for reproducibility, or point us to a source
> > 
> > 
> > The author don't update the code about the part of data augment. Now you can understand that the code only finish the part of semi-training. The 'noise_type' is useless in this repo.
> 
> Were you able to reproduce the results from the paper?

Because I use different data-augment methods and dataset. I only tell you the 2-stage semi-training is efficient.

**Comment by mnishant2** [comment]
> > > > I am facing the same issue, were you able to fix it? I didn't get the answer provided here, what is the code to add noise, could you give the code for reproducibility, or point us to a source
> > > 
> > > 
> > > The author don't update the code about the part of data augment. Now you can understand that the code only finish the part of semi-training. The 'noise_type' is useless in this repo.
> > 
> > 
> > Were you able to reproduce the results from the paper?
> 
> Because I use different data-augment methods and dataset. I only tell you the 2-stage semi-training is efficient.

Do you have a repository that you can point me to for the data augmentation code, that would be really helpful

**Comment by seamoke** [comment]
> > > > > I am facing the same issue, were you able to fix it? I didn't get the answer provided here, what is the code to add noise, could you give the code for reproducibility, or point us to a source
> > > > 
> > > > 
> > > > The author don't update the code about the part of data augment. Now you can understand that the code only finish the part of semi-training. The 'noise_type' is useless in this repo.
> > > 
> > > 
> > > Were you able to reproduce the results from the paper?
> > 
> > 
> > Because I use different data-augment methods and dataset. I only tell you the 2-stage semi-training is efficient.
> 
> Do you have a repository that you can point me to for the data augmentation code, that would be really helpful

https://github.com/makcedward/nlpaug
I use this repo, I hope it will solve your problem.
